### ISSUE TITLE
Support for Xamarin.Forms WinRT/Windows Phone 8.1 WCF Client ?

### ISSUE THREAD

**Issue by abrasat** [mallibone/WcfIntegrationXamarinForms#1]
Is there any possibility to get the WCF client code from the sample working also for applications targeting PCL profile 259 (support for WinRT/WindowsPhone 8.1), as System.ServiceModel namespace not available for that profile.

**Comment by mallibone** [comment]
Hey @abrasat sorry for the delay bit busy lately. I have not yet tried to use it with the 259 profile but will try to look in to it and would then get back to you.

**Comment by mallibone** [comment]
Hey @abrasat it looks like Windows Phone 8.1 (RT) does not support the WCF client. You will have to use the Silverlight profile/application approach. But it looks though like support will be back in Win10.
